services:
  adminer-db:
    image: 'mariadb'
    container_name: sql-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --innodb-buffer-pool-size=128M 
    volumes:
      - "${APP_DATA_DIR}/data/mysql:/var/lib/mysql"
      - "${APP_DATA_DIR}/etc/mysql:/etc/mysql"
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.sabnzbd-web-redirect.redirectscheme.scheme: https
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
      #runtipi.managed: true