services:
  spotweb:
    image: jgeusebroek/spotweb
    container_name: spotweb
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - 'spotweb-db'
    environment:
      TZ: Europe/Amsterdam
      CRON_INTERVAL: '*/5 * * * *'
      DB_HOST: "spotweb-db"
#      DB_ENGINE: "pdo_mysql"
#      DB_PORT: "3306"
      DB_ENGINE: "pdo_pgsql"
      DB_PORT: "5432"
      DB_NAME: "spotweb"
      DB_USER: "spotweb"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ${APP_DATA_DIR}/spotweb/config:/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.sabnzbd-web-redirect.redirectscheme.scheme: https
      traefik.http.services.sabnzbd.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.sabnzbd-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sabnzbd-insecure.entrypoints: web
      traefik.http.routers.sabnzbd-insecure.service: spotweb
      traefik.http.routers.sabnzbd-insecure.middlewares: spotweb-web-redirect
      # Websecure
      traefik.http.routers.sabnzbd.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sabnzbd.entrypoints: websecure
      traefik.http.routers.sabnzbd.service: spotweb
      traefik.http.routers.sabnzbd.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.sabnzbd-local-insecure.rule: Host(`spotweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.sabnzbd-local-insecure.entrypoints: web
      traefik.http.routers.sabnzbd-local-insecure.service: spotweb
      traefik.http.routers.sabnzbd-local-insecure.middlewares: spotweb-web-redirect
      # Local domain secure
      traefik.http.routers.sabnzbd-local.rule: Host(`spotweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.sabnzbd-local.entrypoints: websecure
      traefik.http.routers.sabnzbd-local.service: spotweb
      traefik.http.routers.sabnzbd-local.tls: true
      runtipi.managed: true

  spotweb-db:
    container_name: spotweb-db
    restart: unless-stopped

#    image: 'mariadb'
#    environment:
#      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#      MYSQL_USER: spotweb
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#      MYSQL_DATABASE: spotweb
#    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --innodb-buffer-pool-size=128M 
#    volumes:
#      - "${APP_DATA_DIR}/data/mysql:/var/lib/mysql"

    image: postgres:17
    volumes:
      - ${APP_DATA_DIR}/postgresql/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:  "${DB_PASSWORD}"
      POSTGRES_USER: spotweb
      POSTGRES_DB: spotweb

    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true